// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lohmzywgbkntvpuygvfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvaG16eXdnYmtudHZwdXlndmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjYyNDUsImV4cCI6MjA2ODAwMjI0NX0.FCiA9ps4QYto38P0-sZcNcR3YtOJba9GV3PGeMwKuds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});